# -*- coding: utf-8 -*-
"""Reto5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xhWD3HxsXqeTsgzM91tEdvCjVhwobfJA

#Julio 31
"""

lista = [3,4,5,6]

print(lista[2])

lista[2] = 10
print(lista)

lista.append(40)
print(lista)

lista.remove(40)
print(lista)

lista.pop(3)
print(lista)

lista.pop(-1)
print(lista)

lista = [4,5,6,8]

lista[-1]

lista.pop(-1)
print(lista)

print(lista[::-1])

diccionario = {2:30, 3:59, 6:70}

print(diccionario[3])

diccionario.get(3)

diccionario.pop(6)
print(diccionario)

diccionario.update({6:70})
print(diccionario)

len(diccionario)

diccionario[9] = 60
print(diccionario)

diccionario.update({9:61})
print(diccionario)

diccionario[9] = 60
print(diccionario)

inventario = {
    1: ['peras', 1200.0, 4], 
    2: ['arroz', 10000.0, 5], 
    3: ['papas', 500.0, 4] 
    }


inventario[1][1]

inventario.get(1)[1]

inventario = {
    1: ['peras', 1200.0, 4], 
    2: ['arroz', 10000.0, 5], 
    3: ['papas', 500.0, 4] 
    }

v_mayor = 0
for i in inventario:
  if inventario[i][1] > v_mayor:
    v_mayor = inventario[i][1]
    n_mayor = inventario[i][0]

#i=1, inventario[1][1] = 1200.0 > 0, v_mayor = 1200.0
#i=2,  inventario[2][1] = 10000.0 > 1200.0, v_mayor = 10000.0
#i=3, inventario[3][1] = 500.0 > 10000.0, v_mayor = 10000.0
print(n_mayor)

v_menor = v_mayor
for i in inventario:
  if inventario[i][1] < v_menor:
    v_menor = inventario[i][1]
    n_menor = inventario[i][0]

print(n_menor)

v_menor = 999999999999
for i in inventario:
  if inventario[i][1] < v_menor:
    v_menor = inventario[i][1]
    n_menor = inventario[i][0]

print(n_menor)

float('inf')

v_menor = float('inf')
for i in inventario:
  if inventario[i][1] < v_menor:
    v_menor = inventario[i][1]
    n_menor = inventario[i][0]

print(n_menor)

import math

v_menor = math.inf
for i in inventario:
  if inventario[i][1] < v_menor:
    v_menor = inventario[i][1]
    n_menor = inventario[i][0]

print(n_menor)

inventario = {
    1: ['peras', 1200.0, 4],
    2: ['arroz', 10000.0, 5], 
    3: ['papas', 500.0, 4] 
    }

clave = list(inventario.keys())[0]
v_menor = inventario[clave][1]
for i in inventario:
  if inventario[i][1] < v_menor:
    v_menor = inventario[i][1]
    n_menor = inventario[i][0]

print(n_menor)

list(inventario.keys())[0]

def potencia(base, expo):
  total = base**expo
  return total

print(potencia(4, 2))

def potencia(base, expo):
  total = base**expo
  return total

p = potencia(4, 2) #p=16
print(p)

def imprimir():
  print('hola')


imprimir()

def imprimir():
  print('hola')

c = imprimir()
print(c)

inventario = {
    1: ['peras', 1200.0, 4], 
    2: ['arroz', 10000.0, 5], 
    3: ['papas', 500.0, 4] 
    }

def borrar(error): #error = False
  if cod in inventario:
    inventario.pop(cod)
  else:
    error = True
  return error
#Definir funciones, variables....


#input()...
op = input()
producto = input().split()
cod = int(producto[0])
error = False

#codicionales
if op == "BORRAR":
  error = borrar(error) #error = True
#elif op == "AGREGAR":
#  error = agregar(error)


#llamar las funciones de nombre mayor, menor, promedio e inventario


if error:
  print('ERROR')
else:
  print("nMayor, nMenor, promedio, inventario")

lista = [5,6,7]

10 in lista

BORRAR
3 papas 3000 4

